### ISSUE TITLE
First Deploy: 404 fetching html assets

### ISSUE THREAD

**Issue by idusortus** [NetCoreTemplates/razor-ssg#1]
Thanks for this!

Renders poorly on the github page, unable to reach various style assets. I didn't modify anything. I created the project a few times and did so on two different organizations.

Renders fine running off of localhost.

[Example](https://thedeperejohnsons.github.io/site/)

I'll follow-up if I find the time to debug, was just taking a look around & thought you'd like to be aware.

Enjoy,
Sam

**Comment by mythz** [comment]
This was due to a bug in the build.yml GitHub Action which should be resolved from this commit:

https://github.com/NetCoreTemplates/razor-ssg/commit/67b6bd04d03556254a7b9e3d8abb869181e938ff

So it should now be resolved if you update your build.yml or create a new project from this template.

thx for reporting!
